### ISSUE TITLE
Auto register dependencies

### ISSUE THREAD

**Issue by alexalok** [alexalok/dotWork#7]
Detect dependencies from ctor and ExecuteIteration and autoregister them as singleton or scoped respectively.

Caveats:
- [ ] do we re-register deps?
- [ ] do we register them by an implementation or an interface?
- [ ] do we support optional deps?
- [ ] what about nested deps?

Source: https://habr.com/ru/post/587518/comments/#comment_23672074

**Comment by mishamyte** [comment]
As for me it is kinda strange concept, uncharacteristic for .NET ecosystem.

It could cause a lot of strange behaviors (if user does not register dependencies explicitly or via kinda scan, defined explicitly).
And could cause a lot of bugs.

But if you will implement this feature, think about case with multiple registrations

**Comment by alexalok** [comment]
I am thinking about explicit dependency auto registration, i.e. `.AddWorks().WithDependencies()`. I do agree that doing that implicitly is a no-go.

**Comment by alexalok** [comment]
After evaluating all the options, I've decided to drop this feature altogether. There are other libraries available (i.e. [Scrutor](https://github.com/khellang/Scrutor)) that provide user with convenience methods for dependency registration. Adding our own registration methods is out of scope of dotWork responsibility.
